### ISSUE TITLE
Update plan for the helm charts with respect to the app version changes

### ISSUE THREAD

**Issue by beingamarnath** [vouch/helm-charts#12]
Appreciate you offering your time to enable this helm chart. Currently I see the app version is lacking behind. How are you planning on keeping up with the app changes here? Are you open for PR's or can you quickly update this to support the latest versions?

**Comment by halkeye** [comment]
yea there's https://github.com/halkeye-helm-charts/vouch/pull/11 which just needs an chart.yaml change

I honestly havn't touched this chart in so long, I need to spend some time this weekend to give it a bunch of love and get it all updated. Vouch is one of those things that has just worked and I never really needed to put any thought into it.

**Comment by punkle** [comment]
I have recently updated the app version to the most recent version 0.36, it should track the reviews of this minor version. Please let me know if there is anything else we can help with.

**Comment by bnfinet** [comment]
@punkle you've done such nice work getting this all setup.  Thank you!

**Comment by punkle** [comment]
No probs.
